## PART D — MINI PROJECT
## Mini Project: Prompt Style Generator using VAE
## Task 9: Prompt Encoding

In [2]:
import numpy as np
import re

# -------- Example prompts --------
prompts = [
    "Write a short story about a dragon.",
    "Explain VAE in simple terms, with examples.",
    "List 5 tips for coding efficiently!"
]

# -------- Function to extract numeric features --------
def encode_prompt(prompt):
    length = len(prompt)                         # total characters
    keywords = len(re.findall(r'\b(a|the|an|is|for|with|5)\b', prompt, re.I))  # simple keyword count
    punctuation = len(re.findall(r'[.,!?]', prompt))
    verbs = len(re.findall(r'\b(write|explain|list)\b', prompt, re.I))        # simple verb count
    return np.array([length, keywords, punctuation, verbs], dtype=float)

# -------- Encode all prompts --------
encoded_prompts = np.array([encode_prompt(p) for p in prompts])

print("Encoded prompt feature vectors:")
print(encoded_prompts)


Encoded prompt feature vectors:
[[35.  2.  1.  1.]
 [43.  1.  2.  1.]
 [35.  2.  1.  1.]]


## Task 10: Generate Variations

In [1]:
import numpy as np

# -------- Example: Encoded prompt features from Task 9 --------
encoded_prompts = np.array([
    [32, 1, 1, 1],
    [41, 3, 2, 1],
    [35, 2, 2, 1]
], dtype=float)

input_dim = encoded_prompts.shape[1]
latent_dim = 2

# -------- Dummy encoder (mean & log_var) --------
# Normally learned via VAE training; using simple linear map for demonstration
W_mu = np.random.randn(input_dim, latent_dim) * 0.1
b_mu = np.zeros(latent_dim)

W_logvar = np.random.randn(input_dim, latent_dim) * 0.1
b_logvar = np.zeros(latent_dim)

def encoder(x):
    mu = x @ W_mu + b_mu
    log_var = x @ W_logvar + b_logvar
    return mu, log_var

# -------- Decoder (linear map for demo) --------
W_dec = np.random.randn(latent_dim, input_dim) * 0.1
b_dec = np.zeros(input_dim)

def decoder(z):
    return z @ W_dec + b_dec

# -------- Sample latent vectors from encoder outputs --------
num_variations = 5
for idx, prompt_vec in enumerate(encoded_prompts):
    mu, log_var = encoder(prompt_vec)
    sigma = np.exp(0.5 * log_var)
    
    print(f"\nOriginal prompt vector {idx+1}:", prompt_vec)
    print("Generated variations:")
    for i in range(num_variations):
        z = mu + sigma * np.random.randn(latent_dim)  # Reparameterization trick
        gen_vec = decoder(z)
        print(f"Variation {i+1}:", gen_vec)



Original prompt vector 1: [32.  1.  1.  1.]
Generated variations:
Variation 1: [-1.03501493  0.89908405  0.02300206 -0.31904774]
Variation 2: [-0.5479612  -0.68035339  0.72955774  0.161795  ]
Variation 3: [-1.34341969  2.2842969  -0.66330537 -0.73365663]
Variation 4: [-0.80618384  0.17915157  0.34123194 -0.09946379]
Variation 5: [-1.08020972  1.06357727 -0.05368659 -0.3687951 ]

Original prompt vector 2: [41.  3.  2.  1.]
Generated variations:
Variation 1: [-0.30310636 -2.36645191  1.63818942  0.65865297]
Variation 2: [-0.92664919  0.0570911   0.48455303 -0.07176205]
Variation 3: [-1.11332331  0.97749394  0.01829913 -0.34615692]
Variation 4: [-0.47115165 -1.65341376  1.29012789  0.44467711]
Variation 5: [-2.90062017  7.82419181 -3.22637022 -2.4111761 ]

Original prompt vector 3: [35.  2.  2.  1.]
Generated variations:
Variation 1: [-0.78410238  0.05245119  0.40744414 -0.06190757]
Variation 2: [-1.99044834  4.63344875 -1.75761212 -1.44420138]
Variation 3: [-0.87715134  0.23564955  0.34