## PART D — MINI PROJECT (True Generative AI Entry)
## Mini Project: Latent Representation Generator for Prompts
## Task 9: Encode Prompts

In [3]:
import numpy as np

prompts = [
    "Write a short story about a robot.",
    "Explain photosynthesis in simple words.",
    "List 3 benefits of exercise!"
]

def encode_prompt(prompt):
    length = len(prompt)
    keywords = len([w for w in prompt.split() if w.lower() in ["robot", "story", "photosynthesis", "exercise"]])
    punctuation = sum([1 for c in prompt if c in ".,!?"])
    verbs = len([w for w in prompt.split() if w.lower() in ["write", "explain", "list"]])
    return [length, keywords, punctuation, verbs]

X = np.array([encode_prompt(p) for p in prompts], dtype=float)

# Min-max normalization safely
X_min = X.min(axis=0)
X_max = X.max(axis=0)
X_norm = (X - X_min) / np.where((X_max - X_min)==0, 1, X_max - X_min)

print("Encoded & normalized prompts:\n", X_norm)


Encoded & normalized prompts:
 [[0.54545455 1.         0.         0.        ]
 [1.         1.         0.         0.        ]
 [0.         0.         0.         0.        ]]


## Task 10: Latent Space Exploration

In [8]:
import numpy as np

# -----------------------------
# Step 0: Tiny dataset
# -----------------------------
# 5 samples, 4 features
X = np.random.rand(5, 4)
print("Original data:\n", X)

# -----------------------------
# Step 1: Define encoder
# -----------------------------
# Encode 4D input into 2D latent space
W_enc = np.random.rand(4, 2)  # weights
b_enc = np.random.rand(2)     # bias

def encoder(X):
    return X @ W_enc + b_enc   # linear encoding

# -----------------------------
# Step 2: Define decoder
# -----------------------------
# Decode 2D latent vector back to 4D
W_dec = np.random.rand(2, 4)  # weights
b_dec = np.random.rand(4)     # bias

def decoder(Z):
    return Z @ W_dec + b_dec   # linear reconstruction

# -----------------------------
# Step 3: Encode
# -----------------------------
latent_vectors = encoder(X)
print("\nLatent vectors:\n", latent_vectors)

# -----------------------------
# Step 4: Add small noise
# -----------------------------
noise = np.random.normal(0, 0.05, latent_vectors.shape)
noisy_latent = latent_vectors + noise

# -----------------------------
# Step 5: Decode
# -----------------------------
original_recon = decoder(latent_vectors)
noisy_recon = decoder(noisy_latent)

print("\nOriginal reconstruction:\n", original_recon)
print("\nNoisy reconstruction:\n", noisy_recon)

# ---


Original data:
 [[0.61293198 0.95566659 0.12541909 0.14726631]
 [0.92907112 0.83298853 0.27266785 0.60388947]
 [0.78444918 0.97204364 0.31281371 0.03907026]
 [0.05688799 0.08604395 0.22321091 0.69057453]
 [0.03536075 0.97896784 0.19843841 0.09148798]]

Latent vectors:
 [[0.45972624 1.95793998]
 [0.48649532 2.31697903]
 [0.49019258 2.14682031]
 [0.26702485 1.11817687]
 [0.4191041  1.50979679]]

Original reconstruction:
 [[0.87672331 2.23126721 2.80558564 1.91096303]
 [1.00475369 2.48633564 3.13297849 2.11614609]
 [0.94879679 2.36968654 2.98327424 2.02834812]
 [0.53979074 1.60105625 1.99651542 1.35606925]
 [0.71484199 1.91103385 2.39454133 1.65070306]]

Noisy reconstruction:
 [[0.91363897 2.27763136 2.86520458 1.98000643]
 [1.0056734  2.4837205  3.12963955 2.11923694]
 [0.94906407 2.3730133  2.98753316 2.02776058]
 [0.54326197 1.59998767 1.99517565 1.364535  ]
 [0.69350449 1.85539755 2.3231817  1.62127965]]
